name: Presto Release Workflow

on:
  workflow_dispatch:

jobs:
  presto-release:
    name: Presto Release Workflow
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout Presto source
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y awscli git jq make python3 python3-venv tree

      - name: Configure Git
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.email "oss-release-bot@prestodb.io"
          git config --global user.name "oss-release-bot"
          git config pull.rebase false

      - name: Set Maven version
        run: |
          unset MAVEN_CONFIG && ./mvnw versions:set -DremoveSnapshot -ntp

      - name: Get Presto release version
        id: get-version
        run: |
          PRESTO_RELEASE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
            -Dexpression=project.version -q -ntp -DforceStdout | tail -n 1)
          echo "PRESTO_RELEASE_VERSION=$PRESTO_RELEASE_VERSION" >> $GITHUB_ENV

      - name: Update version in master
        run: |
          git reset --hard
          unset MAVEN_CONFIG && ./mvnw release:prepare --batch-mode \
            -DskipTests \
            -DautoVersionSubmodules \
            -DdevelopmentVersion=${{ env.PRESTO_RELEASE_VERSION }} \
            -DreleaseVersion=${{ env.PRESTO_RELEASE_VERSION }}
          git push --follow-tags origin master

      - name: Push release branch
        run: |
          git checkout -b release-${{ env.PRESTO_RELEASE_VERSION }}
          git push origin release-${{ env.PRESTO_RELEASE_VERSION }}
